/**
 * orderIndex should be added dinamically, based on the current screens in the campaign, by default it's 3
 * screenId should be generated with uuid
 * campaignId should be added based on the current campaign
 */
export const EndScreenFailureTemplate = {
	type: "endFailure",
	orderIndex: 3,
	background: {
		type: "gradient",
		color: "linear-gradient(to bottom, #ed213a, #93291e)",
	},
	screenId: "GENERATE",
	campaignId: "ADD",
};

/**
 * itemId should be generated with uuid
 * screenId should be added based on the current screen - this is the object id of the screen in the db
 */
export const EndScreenFailureTemplateItems = [
	{
		type: "text",
		orderIndex: 0,
		itemId: "GENERATE",
		screenId: "ADD",
		content: "😢",
		src: "",
		settings: {
			fontFamily: "",
			fontSize: 64,
			color: {
				r: 51,
				g: 51,
				b: 51,
				a: 1,
			},
			highlightColor: {
				type: "solid",
				background: {},
				backgroundColor: "",
			},
			bold: true,
			italic: false,
			underline: false,
			uppercase: false,
			align: "center",
			classNames: "",
			width: 251,
			height: 95,
			top: 73,
			left: 35,
			translateX: 16,
			translateY: 0,
			rotate: 0,
		},
	},
	{
		type: "text",
		orderIndex: 1,
		itemId: "GENERATE",
		screenId: "ADD",
		content: "Oh, snap...",
		src: "",
		settings: {
			fontFamily: "",
			fontSize: 20,
			color: {
				r: 255,
				g: 255,
				b: 255,
				a: 1,
			},
			highlightColor: {
				type: "solid",
				background: {},
				backgroundColor: "",
			},
			bold: true,
			italic: false,
			underline: false,
			uppercase: false,
			align: "center",
			classNames: "",
			width: 214,
			height: 30,
			top: 196,
			left: 40,
			translateX: 30,
			translateY: 3,
			rotate: 0,
		},
	},
	{
		type: "text",
		orderIndex: 2,
		itemId: "GENERATE",
		screenId: "ADD",
		content: "You need more correct answers to successfully complete the quiz. Let's try it again.",
		src: "",
		settings: {
			fontFamily: "",
			fontSize: 20,
			color: {
				r: 255,
				g: 255,
				b: 255,
				a: 1,
			},
			highlightColor: {
				type: "solid",
				background: {},
				backgroundColor: "",
			},
			bold: false,
			italic: false,
			underline: false,
			uppercase: false,
			align: "center",
			classNames: "",
			width: 293,
			height: 96,
			top: 297,
			left: 32,
			translateX: -1,
			translateY: 0,
			rotate: 0,
		},
	},
	{
		type: "button",
		orderIndex: 3,
		itemId: "GENERATE",
		screenId: "ADD",
		content: "👉 TRY AGAIN 👈",
		src: "",
		settings: {
			fontFamily: "",
			fontSize: 18,
			color: {
				r: 208,
				g: 2,
				b: 27,
				a: 1,
			},
			highlightColor: {
				type: "gradient",
				background: {},
				backgroundColor: "linear-gradient(45deg, #85FFBD 0%, #FFFB7D 100%)",
			},
			bold: true,
			italic: false,
			underline: false,
			uppercase: false,
			align: "center",
			classNames: "screen-button screen-button--classic",
			width: 200,
			height: 50,
			top: 442,
			left: 76,
			translateX: 0,
			translateY: 0,
			rotate: 0,
			action: "restart",
		},
	},
];
