/**
 * screenId should be generated with uuid
 * campaignId should be added based on the current campaign
 */
export const StartScreenTemplate = {
	type: "start",
	orderIndex: 0,
	background: {
		type: "gradient",
		color: "linear-gradient(161.74deg, #A425B6 9.18%, #E64CA8 50%, #F55F7E 92.56%)",
	},
	screenId: "GENERATE",
	campaignId: "ADD",
};

/**
 * itemId should be generated with uuid
 * screenId should be added based on the current screen - this is the object id of the screen in the db
 */
export const StartScreenTemplateItems = [
	{
		type: "button",
		orderIndex: 0,
		itemId: "GENERATE",
		screenId: "ADD",
		content: "Let's go",
		src: "",
		settings: {
			fontFamily: "",
			fontSize: 18,
			color: {
				r: 255,
				g: 255,
				b: 255,
				a: 1,
			},
			highlightColor: {
				type: "gradient",
				backgroundColor: "linear-gradient(to bottom, #ed213a, #93291e)",
			},
			bold: true,
			italic: false,
			underline: false,
			uppercase: true,
			align: "center",
			classNames: "screen-button screen-button--classic",
			width: 200,
			height: 50,
			top: 500,
			left: 88,
			translateX: -10,
			translateY: 0,
			rotate: 0,
		},
	},
	{
		type: "text",
		orderIndex: 1,
		itemId: "GENERATE",
		screenId: "ADD",
		content: "👉 Double click to edit the text 👈",
		src: "",
		settings: {
			fontFamily: "",
			fontSize: 28,
			color: {
				r: 255,
				g: 255,
				b: 255,
				a: 1,
			},
			highlightColor: {
				type: "solid",
				backgroundColor: "",
			},
			bold: true,
			italic: false,
			underline: false,
			uppercase: false,
			align: "center",
			classNames: "",
			width: 251,
			height: 86,
			top: 100,
			left: 52,
			translateX: -1,
			translateY: 0,
			rotate: 0,
		},
	},
	{
		type: "text",
		orderIndex: 2,
		itemId: "GENERATE",
		screenId: "ADD",
		content: "This is the first screen participants will see. It is a good practice to add some important information about your campaign here.",
		src: "",
		settings: {
			fontFamily: "",
			fontSize: 16,
			color: {
				r: 255,
				g: 255,
				b: 255,
				a: 1,
			},
			highlightColor: {
				type: "solid",
				background: {},
				backgroundColor: "",
			},
			bold: true,
			italic: false,
			underline: false,
			uppercase: false,
			align: "left",
			classNames: "",
			width: 266,
			height: 102,
			top: 205,
			left: 36,
			translateX: 16,
			translateY: 141,
			rotate: 0,
		},
	},
	{
		type: "text",
		orderIndex: 3,
		itemId: "GENERATE",
		screenId: "ADD",
		content: "👈 Drag & Drop text, buttons, images and stickers form the sidebar on the left",
		src: "",
		settings: {
			fontFamily: "",
			fontSize: 20,
			color: {
				r: 248,
				g: 231,
				b: 28,
				a: 1,
			},
			highlightColor: {
				type: "solid",
				background: {},
				backgroundColor: "",
			},
			bold: true,
			italic: false,
			underline: false,
			uppercase: false,
			align: "left",
			classNames: "",
			width: 290,
			height: 89,
			top: 210,
			left: 36,
			translateX: 1,
			translateY: 0,
			rotate: 0,
		},
	},
];
