const ButtonTypes = [
	{
		name: `Classic Button`,
		content: `Classic Button`,
		settings: {
			fontFamily: ``,
			fontSize: 18,
			color: {
				r: 255,
				g: 255,
				b: 255,
				a: 1,
			},
			highlightColor: {
				type: "solid",
				background: {},
				backgroundColor: "#425d74",
			},
			bold: true,
			italic: false,
			underline: false,
			uppercase: false,
			align: `center`,
			classNames: `screen-button screen-button--classic`,
			width: 200,
			height: 50,
		},
	},
	{
		name: `Square Button`,
		content: `Square Button`,
		settings: {
			fontFamily: ``,
			fontSize: 18,
			color: {
				r: 255,
				g: 255,
				b: 255,
				a: 1,
			},
			highlightColor: {
				type: "solid",
				background: {},
				backgroundColor: "#425d74",
			},
			bold: true,
			italic: false,
			underline: false,
			uppercase: false,
			align: `center`,
			classNames: `screen-button screen-button--square`,
			width: 200,
			height: 50,
		},
	},
	{
		name: `Rounded Button`,
		content: `Rounded Button`,
		settings: {
			fontFamily: ``,
			fontSize: 18,
			color: {
				r: 255,
				g: 255,
				b: 255,
				a: 1,
			},
			highlightColor: {
				type: "solid",
				background: {},
				backgroundColor: "#425d74",
			},
			bold: true,
			italic: false,
			underline: false,
			uppercase: false,
			align: `center`,
			classNames: `screen-button screen-button--rounded`,
			width: 200,
			height: 50,
		},
	},
	/* {
		name: `Square Outlined`,
		content: `Square Outlined`,
		settings: {
			fontFamily: ``,
			fontSize: 18,
			color: {
				r: 255,
				g: 255,
				b: 255,
				a: 1,
			},
			highlightColor: {
				type: "solid",
				background: {},
				backgroundColor: "#425d74",
			},
			bold: true,
			italic: false,
			underline: false,
			uppercase: false,
			align: `center`,
			classNames: `screen-button screen-button--square-outlined`,
			width: 200,
			height: 50,
		},
	},
	{
		name: `Rounded Outlined`,
		content: `Rounded Outlined`,
		settings: {
			fontFamily: ``,
			fontSize: 18,
			color: {
				r: 255,
				g: 255,
				b: 255,
				a: 1,
			},
			highlightColor: {
				type: "solid",
				background: {},
				backgroundColor: "#425d74",
			},
			bold: true,
			italic: false,
			underline: false,
			uppercase: false,
			align: `center`,
			classNames: `screen-button screen-button--rounded-outlined`,
			width: 200,
			height: 50,
		},
	}, */
];

export default ButtonTypes;
