const FontFamilies = {
	abrilFatface: {
		name: "Abril Fatface",
		key: "abril-fatface",
		fontFamily: "'Abril Fatface', cursive;",
		url: "https://fonts.googleapis.com/css2?family=Abril+Fatface&display=swap",
	},
	alegreya: {
		name: "Alegreya",
		key: "alegreya",
		fontFamily: "'Alegreya', serif;",
		url: "https://fonts.googleapis.com/css2?family=Alegreya:ital,wght@0,400;0,700;1,400;1,700&display=swap",
	},
	arial: {
		name: "Arial",
		key: "arial",
		fontFamily: "Arial, Helvetica, sans-serif;",
		url: "",
	},
	arvo: {
		name: "Arvo",
		key: "arvo",
		fontFamily: "'Arvo', serif;",
		url: "https://fonts.googleapis.com/css2?family=Arvo:ital,wght@0,400;0,700;1,400;1,700&display=swap",
	},
	biorhyme: {
		name: "Biorhyme",
		key: "biorhyme",
		fontFamily: "'BioRhyme', serif;",
		url: "https://fonts.googleapis.com/css2?family=BioRhyme:wght@400;700&display=swap",
	},
	cardo: {
		name: "Cardo",
		key: "cardo",
		fontFamily: "'Cardo', serif;",
		url: "https://fonts.googleapis.com/css2?family=Cardo:ital,wght@0,400;0,700;1,400&display=swap",
	},
	comicSans: {
		name: "Comic Sans",
		key: "comic-sans",
		fontFamily: "'Comic Sans MS', 'Comic Sans', cursive;",
		url: "",
	},
	concertOne: {
		name: "Concert One",
		key: "concert-one",
		fontFamily: "'Concert One', cursive;",
		url: "https://fonts.googleapis.com/css2?family=Concert+One&display=swap",
	},
	courierNew: {
		name: "Courier New",
		key: "courier-new",
		fontFamily: "'Courier New', Courier, monospace;",
		url: "",
	},
	frankRuhlLibre: {
		name: "Frank Ruhl Libre",
		key: "frank-ruhl-libre",
		fontFamily: "'Frank Ruhl Libre', serif;",
		url: "https://fonts.googleapis.com/css2?family=Frank+Ruhl+Libre:wght@400;700&display=swap",
	},
	georgia: {
		name: "Georgia",
		key: "georgia",
		fontFamily: "Georgia, 'Times New Roman', Times, serif;",
		url: "",
	},
	lato: {
		name: "Lato",
		key: "lato",
		fontFamily: "'Lato', sans-serif;",
		url: "https://fonts.googleapis.com/css2?family=Lato:ital,wght@0,400;0,700;1,400;1,700&display=swap",
	},
	montserrat: {
		name: "Montserrat",
		key: "montserrat",
		fontFamily: "'Montserrat', sans-serif;",
		url: "https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,400;0,700;1,400;1,700&display=swap",
	},
	nunito: {
		name: "Nunito",
		key: "nunito",
		fontFamily: "'Nunito', sans-serif;",
		url: "https://fonts.googleapis.com/css2?family=Nunito:ital,wght@0,400;0,700;1,400;1,700&display=swap",
	},
	oldStandardTt: {
		name: "Old Standard TT",
		key: "old-standard-tt",
		fontFamily: "'Old Standard TT', serif;",
		url: "https://fonts.googleapis.com/css2?family=Old+Standard+TT:ital,wght@0,400;0,700;1,400&display=swap",
	},
	openSans: {
		name: "Open Sans",
		key: "open-sans",
		fontFamily: "'Open Sans', sans-serif;",
		url: "https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,400;0,700;1,400;1,700&display=swap",
	},
	oswald: {
		name: "Oswald",
		key: "oswald",
		fontFamily: "'Oswald', sans-serif;",
		url: "https://fonts.googleapis.com/css2?family=Oswald:wght@400;700&display=swap",
	},
	playfairDisplay: {
		name: "Playfair Display",
		key: "playfair-display",
		fontFamily: "'Playfair Display', serif;",
		url: "https://fonts.googleapis.com/css2?family=Playfair+Display:ital,wght@0,400;0,700;1,400;1,700&display=swap",
	},
	ptSans: {
		name: "PT Sans",
		key: "pt-sans",
		fontFamily: "'PT Sans', sans-serif;",
		url: "https://fonts.googleapis.com/css2?family=PT+Sans:ital,wght@0,400;0,700;1,400;1,700&display=swap",
	},
	raleway: {
		name: "Raleway",
		key: "raleway",
		fontFamily: "'Raleway', sans-serif;",
		url: "https://fonts.googleapis.com/css2?family=Raleway:ital,wght@0,400;0,700;1,400;1,700&display=swap",
	},
	roboto: {
		name: "Roboto",
		key: "roboto",
		fontFamily: "'Roboto', sans-serif;",
		url: "https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,400;0,700;1,400;1,700&display=swap",
	},
	robotoCondensed: {
		name: "Roboto Condensed",
		key: "roboto-condensed",
		fontFamily: "'Roboto Condensed', sans-serif;",
		url: "https://fonts.googleapis.com/css2?family=Roboto+Condensed:ital,wght@0,400;0,700;1,400;1,700&display=swap",
	},
	slabo: {
		name: "Slabo",
		key: "slabo",
		fontFamily: "'Slabo 27px', serif;",
		url: "https://fonts.googleapis.com/css2?family=Slabo+27px&display=swap",
	},
	sourceSansPro: {
		name: "Source Sans Pro",
		key: "source-sans-pro",
		fontFamily: "'Source Sans Pro', sans-serif;",
		url: "https://fonts.googleapis.com/css2?family=Source+Sans+Pro:ital,wght@0,400;0,700;1,400;1,700&display=swap",
	},
	titilliumWeb: {
		name: "Titillium Web",
		key: "titillium-web",
		fontFamily: "'Titillium Web', sans-serif;",
		url: "https://fonts.googleapis.com/css2?family=Titillium+Web:ital,wght@0,400;0,700;1,400;1,700&display=swap",
	},
	verdana: {
		name: "Verdana",
		key: "verdana",
		fontFamily: "Verdana, Geneva, Tahoma, sans-serif;",
		url: "",
	},
	vollkorn: {
		name: "Vollkorn",
		key: "vollkorn",
		fontFamily: "'Vollkorn', serif;",
		url: "https://fonts.googleapis.com/css2?family=Vollkorn:ital,wght@0,400;0,700;1,400;1,700&display=swap",
	},
	yatraOne: {
		name: "Yatra One",
		key: "yatra-one",
		fontFamily: "'Yatra One', cursive;",
		url: "https://fonts.googleapis.com/css2?family=Yatra+One&display=swap",
	},
};

export default FontFamilies;
