const TextTemplates = [
	{
		name: `Headline Text Block`,
		content: `Heading text block`,
		settings: {
			fontFamily: ``,
			fontSize: 28,
			color: {
				r: 51,
				g: 51,
				b: 51,
				a: 1,
			},
			highlightColor: ``,
			bold: true,
			italic: false,
			underline: false,
			uppercase: false,
			align: `left`,
			classNames: ``,
			width: 251,
			height: 42,
		},
	},
	{
		name: `Subheading Text Block`,
		content: `Subheading text block`,
		settings: {
			fontFamily: ``,
			fontSize: 20,
			color: {
				r: 51,
				g: 51,
				b: 51,
				a: 1,
			},
			highlightColor: ``,
			bold: true,
			italic: false,
			underline: false,
			uppercase: false,
			align: `left`,
			classNames: ``,
			width: 214,
			height: 30,
		},
	},
	{
		name: `Body Text Block`,
		content: `Body text block`,
		settings: {
			fontFamily: ``,
			fontSize: 16,
			color: {
				r: 51,
				g: 51,
				b: 51,
				a: 1,
			},
			highlightColor: ``,
			bold: false,
			italic: false,
			underline: false,
			uppercase: false,
			align: `left`,
			classNames: ``,
			width: 113,
			height: 24,
		},
	},
];

export default TextTemplates;
