name: 1-minute-cron
on:
  schedule:
    - cron: '*/1 * * * *'
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Usage reset and overages payment
        run: |
          curl --request POST \
          --url 'https://app.twis.io/api/cron' \
          --header 'Authorization: Bearer ${{ secrets.YOUR_API_KEY }}'